global using Ardalis.Result;
global using Extenso.Data.Entity;
global using Kinnect.Data.Entities;
global using Kinnect.Models;
global using Kinnect.Services.Abstractions;
global using Kinnect.Services.Mapping;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
